#
# Azure Pipelines configuration for building and testing Jest on Linux, Windows, and macOS.
#
    
trigger:
  branches:
    include:
    - '*'  
    - refs/tags/*
    
jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - template: .azure-pipelines-steps.yml

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - script: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        displayName: 'Preserve LF endings and symbolic links on check out'
      - template: .azure-pipelines-steps.yml

  - job: macOS
    pool:
      vmImage: macos-10.13
    steps:
      # This step can be removed once Mercurial gets installed on the macOS image. See https://github.com/Microsoft/azure-pipelines-image-generation/issues/604
      - script: HOMEBREW_NO_AUTO_UPDATE=1 brew install mercurial
        displayName: 'Install Mercurial'
      - template: .azure-pipelines-steps.yml

  - job: GitHub_Release
    displayName: Release on GitHub
    dependsOn: 
    - Windows
    - macOs
    - Linux
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v24.'))  
    steps:
    - task: GitHubRelease@0
      displayName: 'GitHub release (create)'
      inputs:
        gitHubConnection: 'github-zenithworks'
        title: Jest - Javascript Testing Framework Release 
        releaseNotesSource: input
        releaseNotes: | 
          \## Jest Release- $(Build.SourceBranchName) 
          [Release notes](https://github.com/facebook/jest/blob/master/CHANGELOG.md)   |   [Documentation](https://jestjs.io/docs/en/getting-started.html)  |   [Jest Website](https://jestjs.io/en/)     
                    

variables:
  # Used by chalk. Ensures output from Jest includes ANSI escape characters that are needed to match test snapshots.
  FORCE_COLOR: 1

  # Ensures the handful of tests that should be skipped during CI are
  CI: true
